version: '3.3'
services:
#  app:
#    build:
#      context: .
#    depends_on:
#      - mysql
#    ports:
#      - '8080:8080'

  mysql:
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

